name = "packages"
uuid = "943a3ecb-01ea-4a1d-a9d5-3dd833ec53b2"
repo = "https://github.com/keitokurata/packages.git"

[packages]
e8c05ba4723c9c7b719fbe0a991bf17e746e7e25 = { name = "mnist", path = "mnist/src"}
